image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
- port: 8888
  onOpen: open-preview
- port: 3306
  onOpen: ignore

# List the start up tasks. You can start them in parallel in multiple terminals.
# See https://www.gitpod.io/docs/config-start-tasks/
tasks:
- init: composer install && ln -s ~/bin/adminer.php web/adminer.php
  command: mysql -e "CREATE USER 'db'@'localhost' IDENTIFIED by 'db';" ; mysql -e "GRANT ALL PRIVILEGES ON *.* to 'db'@'localhost';" ; mysql -e "CREATE DATABASE db;" ; mysql -e "FLUSH PRIVILEGES;" ; drush sqlc < ./umami_db.sql && drush cr && drush user:pass admin pass ; drush rs 0.0.0.0:8888
  name: Server
- command: echo "Welcome, please allow Server terminal to finish composer and drupal install. It takes a while!" && gp await-port 8888 && drush uli --uri=$(gp url 8888)
  name: Terminal

vscode:
  extensions:
    # PHP extensions.
    - felixfbecker.php-debug
    - wongjn.php-sniffer
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    # Twig extensions.
    - mblode.twig-language-2
